"""Configurable defaults and safety limits for the giveaway system."""

DEFAULT_DURATION_SECONDS = 24 * 60 * 60
DEFAULT_WINNERS = 1
DEFAULT_COLOR = 0xF59E0B
DEFAULT_ALLOW_BOTS = False
DEFAULT_ALLOW_HOST = False
DEFAULT_ALLOW_MULTIPLE_ENTRIES = False
DEFAULT_MAX_ENTRIES_PER_USER = 1
DEFAULT_ALLOW_PREVIOUS_WINNERS = False
MAX_DURATION_SECONDS = 90 * 24 * 60 * 60
MAX_WINNERS = 25
MAX_ENTRIES_PER_USER = 25
SCHEDULER_INTERVAL_SECONDS = 30
DASHBOARD_PAGE_SIZE = 1
REQUIRED_ADMIN_PERMISSION = "manage_guild"
